apiVersion: v1
kind: PersistentVolume
metadata:
  name: lft-nfs-pv
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 100.69.222.7
    path: /srv/lft_results
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lft-results-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
