# Interface secundaria para o pod no Master (Lenovo)
# Equivale ao veth criado pelo LFT entre host e switch OVS no mesmo node
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: lft-link-master
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "bridge",
    "bridge": "lft-br-master",
    "ipam": {
      "type": "host-local",
      "subnet": "10.10.1.0/24",
      "rangeStart": "10.10.1.10",
      "rangeEnd": "10.10.1.50"
    }
  }'
---
# Interface secundaria para o pod no Worker (Destroyer)
# Equivale ao veth criado pelo LFT entre host e switch OVS no mesmo node
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: lft-link-worker
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "bridge",
    "bridge": "lft-br-worker",
    "ipam": {
      "type": "host-local",
      "subnet": "10.10.2.0/24",
      "rangeStart": "10.10.2.10",
      "rangeEnd": "10.10.2.50"
    }
  }'
