apiVersion: v1
kind: PersistentVolume
metadata:
  name: lft-nfs-pv
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: lft
    name: lft-results-pvc
  nfs:
    server: 100.69.222.7
    path: /srv/lft_results
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lft-results-pvc
  namespace: lft
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: lft-nfs-pv
